#%RAML 1.0 DocumentationItem
title: Standard API Template
content:  SC3 and other 3party systems are  independent systems that are looking to build an interface to integrate and automate ticket generation in SC3  for any defects reported in 3rd party systems. There are multiple 3rd party systems ,those who want to integrate with SC3 system for different workflows using REST based APIS.